---
new: true
version: "2"
run:
  concurrency: 6
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - gocyclo
    - unused
    - errorlint
    - loggercheck
    - revive
    - wrapcheck
    - errcheck
linters-settings:
  revive:
    rules:
      - name: if-return
        severity: warning
        disabled: true
      - name: string-format
        severity: warning
        disabled: false
        arguments:
          - - 'core.WriteError[1].Message'
            - '/^([^A-Z]|$)/'
            - must not start with a capital letter
          - - 'fmt.Errorf[0]'
            - '/^([^A-Z]|$)/'
            - must not start with a capital letter
          - - 'fmt.Errorf[0]'
            - '/(^|[^\.!?])$/'
            - must not end in punctuation
          - - panic
            - '/^[^\n]*$/'
            - must not contain line breaks
  gocritic:
    enabled-checks:
      # Diagnostic
      - commentedOutCode
      - nilValReturn
      - weakCond
      - octalLiteral
      - sloppyReassign

      # Performance
      - equalFold
      - indexAlloc
      - rangeExprCopy
      - appendCombine

      # Style
      - boolExprSimplify
      - commentedOutImport
      - docStub
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - methodExprCall
      - stringXbytes
      - typeAssertChain
      - unlabelStmt
      - yodaStyleExpr

      # Opinionated
      - initClause
      - nestingReduce
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock
      - paramTypeCombine
  wrapcheck:
    ignoreSigs:
      # defaults
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      # from kyaml's errors package
      - .WrapPrefixf(
      # from kcmdutil
      - .UsageErrorf(
